In [1]:
import pandas as pd
import upsetplot as up
from matplotlib import pyplot

In [2]:
pd.set_option('display.max_rows', 500)

In [3]:
df = pd.read_csv("../results/permutation_results_20230706_13:45:00")
df

,file_name,bin_size,chrom,alpha_threshold,a,b,pval,num_perms,statistic
0,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,heterochromatin,universe,0.854146,1000,ave_degree
1,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,enhancer,universe,0.990010,1000,ave_degree
2,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,polycomb,universe,0.994006,1000,ave_degree
3,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,promoter,universe,0.541459,1000,ave_degree
4,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,heterochromatin,enhancer,0.051948,1000,ave_degree
...,...,...,...,...,...,...,...,...,...
1915,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,heterochromatin,polycomb,1.000000,1000,ave_degree
1916,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,heterochromatin,promoter,0.991009,1000,ave_degree
1917,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,enhancer,polycomb,0.000999,1000,ave_degree
1918,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,enhancer,promoter,0.004995,1000,ave_degree
1919,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,polycomb,promoter,0.664336,1000,ave_degree

In [4]:
sig_df = df[(df["pval"] < 0.05)|(df["pval"] > 0.95)]
print(f"Number of rows with at least one significant test: {len(sig_df)}")
sig_df

Number of rows with at least one significant test: 1089

,file_name,bin_size,chrom,alpha_threshold,a,b,pval,num_perms,statistic
1,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,enhancer,universe,0.990010,1000,ave_degree
2,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,polycomb,universe,0.994006,1000,ave_degree
5,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr1,0.05,heterochromatin,polycomb,0.043956,1000,ave_degree
10,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr10,0.05,heterochromatin,universe,0.962038,1000,ave_degree
20,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chr11,0.05,heterochromatin,universe,0.023976,1000,ave_degree
...,...,...,...,...,...,...,...,...,...
1914,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,heterochromatin,enhancer,1.000000,1000,ave_degree
1915,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,heterochromatin,polycomb,1.000000,1000,ave_degree
1916,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,heterochromatin,promoter,0.991009,1000,ave_degree
1917,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,enhancer,polycomb,0.000999,1000,ave_degree
1918,Rao_2014_HUVEC_MboI_4DNFIRMZ7QTE.mcool,10000,chrY,0.40,enhancer,promoter,0.004995,1000,ave_degree

In [6]:
sig_df.loc[:, ["a > b"]] = [1 if val  < 0.05 else 0 for val in sig_df["a > b"]]
sig_df.loc[:, ["a < b"]] = [1 if val  < 0.05 else 0 for val in sig_df["a < b"]]
sig_df.loc[:, ["a != b"]] = [1 if val  < 0.05 else 0 for val in sig_df["a != b"]]
sig_df.groupby(["a", "b"]).sum()

/home/stefano/.local/lib/python3.10/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

                          alpha_threshold  bin_size  num_perms  a != b  a > b  \
a               b
Bound           universe            15.26    850000      85000      83     85
enhancer        Bound               15.21    850000      85000      83      1
                polycomb            11.53    650000      65000      54     28
                promoter            10.62    590000      59000      49     27
                universe            11.79    670000      67000      59     30
heterochromatin Bound               14.90    830000      83000      83      0
                enhancer            11.91    680000      68000      64     36
                polycomb            12.05    670000      67000      58     31
                promoter            10.15    580000      58000      51     30
                universe            10.76    610000      61000      58     29
polycomb        Bound               15.32    850000      85000      84      0
                promoter            10.42    590000      59000      52     30
                universe            11.03    620000      62000      57     32
promoter        Bound               14.58    810000      81000      80      1
                universe             9.67    550000      55000      48     26

                          a < b
a               b
Bound           universe      0
enhancer        Bound        84
                polycomb     37
                promoter     32
                universe     37
heterochromatin Bound        83
                enhancer     32
                polycomb     36
                promoter     28
                universe     32
polycomb        Bound        85
                promoter     29
                universe     30
promoter        Bound        80
                universe     29

In [8]:
sig_df[(sig_df["a"] == "1_TssA") & (sig_df["b"] == "Bound") & (sig_df["a < b"] == 1)].sort_values("chrom")

Empty DataFrame
Columns: [file_name, alpha_threshold, bin_size, stat, num_perms, chrom, a, b, a != b, a > b, a < b]
Index: []

In [20]:
sig_df[(sig_df["a"] == "7_Enh") & (sig_df["b"] == "Bound") & (sig_df["a < b"] == 1)].sort_values("chr")

    a != b  a > b  a < b chr      a      b
30       1      0      1   1  7_Enh  Bound
46       1      0      1  10  7_Enh  Bound
42       1      0      1  11  7_Enh  Bound
14       1      0      1  12  7_Enh  Bound
90       1      0      1  13  7_Enh  Bound
2        1      0      1  14  7_Enh  Bound
82       1      0      1  15  7_Enh  Bound
34       1      0      1  17  7_Enh  Bound
66       1      0      1  18  7_Enh  Bound
18       1      0      1   2  7_Enh  Bound
74       1      0      1  20  7_Enh  Bound
10       1      0      1  21  7_Enh  Bound
38       1      0      1   3  7_Enh  Bound
70       1      0      1   4  7_Enh  Bound
50       1      0      1   5  7_Enh  Bound
6        1      0      1   6  7_Enh  Bound
58       1      0      1   7  7_Enh  Bound
54       1      0      1   8  7_Enh  Bound
22       1      0      1   9  7_Enh  Bound
62       1      0      1   X  7_Enh  Bound

In [ ]:
bigger = sig_df.groupby("chr")["a > b"].count()
smaller = sig_df.groupby("chr")["a < b"].count()
differ = sig_df.groupby("chr")["a != b"].count()

chr_df = pd.DataFrame([bigger, smaller, differ]).T
chr_df

In [ ]:
sig_df.sort_values("chr")[0:63]

In [ ]:
upset_df = sig_df.set_index(["a != b", "a < b", "a > b", "a", "b"])
upset_df

In [ ]:
up.plot(upset_df)  
pyplot.show()