WHY IS 118667-118667 STILL IN FILTERED CHROMOSOME 6?????

In [1]:
from cooler import Cooler
from h5py import File

In [18]:
CHROM = "chr6"
PATH_H5PY = "test_files/small.mcool"
PATH_COOL = PATH_H5PY + "::resolutions/10000"
WHY = 118667

In [8]:
my_cool = Cooler(PATH)

In [5]:
lower, upper = my_cool.extent(CHROM)
lower, upper

(106122, 123203)

In [10]:
my_h5py = File(PATH_H5PY)
grp = my_h5py["resolutions/10000"]

In [15]:
lo_id = grp["indexes/bin1_offset"][lower]
hi_id = grp["indexes/bin1_offset"][upper]
lo_id, hi_id

(84395094, 96227603)

In [17]:
chrom_pix = my_cool.pixels()[lo_id:hi_id]
chrom_pix

          bin1_id  bin2_id  count
84395094   106128   238910      1
84395095   106128   148363      1
84395096   106130   164973      1
84395097   106130   180555      1
84395098   106130   191650      1
...           ...      ...    ...
96227598   123196   303107      1
96227599   123196   135836      1
96227600   123196   198902      1
96227601   123196   235364      1
96227602   123196   238869      1

[11832509 rows x 3 columns]

In [19]:
chrom_pix[chrom_pix["bin1_id"]==WHY]

          bin1_id  bin2_id  count
93389987   118667   118667     74
93389988   118667   118673      6
93389989   118667   118675      1
93389990   118667   118680      5
93389991   118667   118681      8
...           ...      ...    ...
93390723   118667   265990      1
93390724   118667   276629      1
93390725   118667   280052      1
93390726   118667   291023      1
93390727   118667   302216      1

[741 rows x 3 columns]

In [22]:
dups = chrom_pix[chrom_pix["bin1_id"]==chrom_pix["bin2_id"]]
dups

          bin1_id  bin2_id  count
84395126   106131   106131      3
84395403   106135   106135      1
84395621   106136   106136     11
84395682   106137   106137     86
84396594   106138   106138    132
...           ...      ...    ...
96227045   123191   123191      1
96227056   123192   123192      9
96227157   123193   123193     33
96227350   123195   123195     11
96227558   123196   123196      1

[16852 rows x 3 columns]

In [25]:
max_bin_diff = -(-200_000_000 // 10_000)
count_thr = 0

indexer = ~((dups["bin2_id"] - dups["bin1_id"] >= max_bin_diff)
            | (dups["count"] <= count_thr)
            | (dups["bin1_id"] == dups["bin2_id"])
            | (dups["bin2_id"] >= upper))
indexer

84395126    False
84395403    False
84395621    False
84395682    False
84396594    False
            ...
96227045    False
96227056    False
96227157    False
96227350    False
96227558    False
Length: 16852, dtype: bool

In [26]:
sum(indexer)

0